### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by grigohas** [celuk/gem5-riscv-linux#1]
Hello i  want to ask for the bootloader and riscv image links for ubuntu 24.04

**Comment by celuk** [comment]
You can find all ubuntu releases here: https://cdimage.ubuntu.com/releases

For ubuntu 24.04 riscv64, you need to use the one for Hifive Unmatched board: https://cdimage.ubuntu.com/releases/24.04/release/ubuntu-24.04-preinstalled-server-riscv64+unmatched.img.xz

For the bootloader firstly try with the one mentioned in [README](http://dist.gem5.org/dist/v22-1/kernels/riscv/static/bootloader-vmlinux-5.10). However, since different ubuntu versions are using different kernel versions it may not be working, I am not sure.

So, either you need to build on by own (e.g.: https://github.com/UCanLinux/riscv64-sample) or you can search it on gem5 resources site:
https://resources.gem5.org/resources?q=architecture%3ARISCV+linux&page=1&sort=relevance&limit=10

Here, 6.6 one might work: 
https://storage.googleapis.com/dist.gem5.org/dist/develop/kernels/riscv/static/linux-6.6.33

**Comment by grigohas** [comment]
6.6.33 isnt wotking, i tried with the given one and linux 24.04 and when i do the controlling i get a "bbl loader" message and the nothing. Do i have to do something more?
